// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: wallets.private.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletsByUserIDRequest) Reset() {
	*x = GetWalletsByUserIDRequest{}
	mi := &file_wallets_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletsByUserIDRequest) ProtoMessage() {}

func (x *GetWalletsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetWalletsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_wallets_private_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletsByUserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetWalletsByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pubkeys       []string               `protobuf:"bytes,5,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletsByUserIDResponse) Reset() {
	*x = GetWalletsByUserIDResponse{}
	mi := &file_wallets_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletsByUserIDResponse) ProtoMessage() {}

func (x *GetWalletsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetWalletsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_wallets_private_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletsByUserIDResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetWalletsByUserIDResponse) GetPubkeys() []string {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

var File_wallets_private_proto protoreflect.FileDescriptor

const file_wallets_private_proto_rawDesc = "" +
	"\n" +
	"\x15wallets.private.proto\x12\x0fwallets.private\"4\n" +
	"\x19GetWalletsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"w\n" +
	"\x1aGetWalletsByUserIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\apubkeys\x18\x05 \x03(\tR\apubkeysJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\bproviderR\vis_verifiedR\x06pubkey2\x7f\n" +
	"\x0eWalletsPrivate\x12m\n" +
	"\x12GetWalletsByUserID\x12*.wallets.private.GetWalletsByUserIDRequest\x1a+.wallets.private.GetWalletsByUserIDResponseB\x04Z\x02./b\x06proto3"

var (
	file_wallets_private_proto_rawDescOnce sync.Once
	file_wallets_private_proto_rawDescData []byte
)

func file_wallets_private_proto_rawDescGZIP() []byte {
	file_wallets_private_proto_rawDescOnce.Do(func() {
		file_wallets_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallets_private_proto_rawDesc), len(file_wallets_private_proto_rawDesc)))
	})
	return file_wallets_private_proto_rawDescData
}

var file_wallets_private_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wallets_private_proto_goTypes = []any{
	(*GetWalletsByUserIDRequest)(nil),  // 0: wallets.private.GetWalletsByUserIDRequest
	(*GetWalletsByUserIDResponse)(nil), // 1: wallets.private.GetWalletsByUserIDResponse
}
var file_wallets_private_proto_depIdxs = []int32{
	0, // 0: wallets.private.WalletsPrivate.GetWalletsByUserID:input_type -> wallets.private.GetWalletsByUserIDRequest
	1, // 1: wallets.private.WalletsPrivate.GetWalletsByUserID:output_type -> wallets.private.GetWalletsByUserIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallets_private_proto_init() }
func file_wallets_private_proto_init() {
	if File_wallets_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallets_private_proto_rawDesc), len(file_wallets_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallets_private_proto_goTypes,
		DependencyIndexes: file_wallets_private_proto_depIdxs,
		MessageInfos:      file_wallets_private_proto_msgTypes,
	}.Build()
	File_wallets_private_proto = out.File
	file_wallets_private_proto_goTypes = nil
	file_wallets_private_proto_depIdxs = nil
}
